#!/usr/bin/env node
// Apollo install — detects the OS and sets up the always-on relay supervisor
// (the one piece that must be running for the extension <-> Hermes bridge).
// Zero dependencies (Node >= 18 stdlib). Idempotent — safe to re-run.
//
//   Windows  -> scheduled task (schtasks, every 10 min watchdog) + VBS launcher
//   Linux    -> systemd --user service (apollo-relay)
//   macOS    -> launchd LaunchAgent (com.apollo.relay)
//
// Run from anywhere:  node <repo>/bridge/install.mjs
//
// What it does NOT do (manual, browser-side): load the unpacked extension in
// Chrome (chrome://extensions -> Developer mode -> Load unpacked -> this repo).

import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RELAY = path.join(REPO, "bridge", "relay.mjs");

// The relay should run under a STABLE node — not Hermes's bundled one, which
// gets restarted (killing its child processes) every time Hermes updates.
// Resolution: APOLLO_NODE env > system node (>= 18) > the node running us.
function pickRelayNode() {
  if (process.env.APOLLO_NODE) return process.env.APOLLO_NODE;
  const candidates =
    process.platform === "win32"
      ? ["C:\\Program Files\\nodejs\\node.exe", "C:\\Program Files (x86)\\nodejs\\node.exe"]
      : ["/usr/bin/node", "/usr/local/bin/node", "/opt/homebrew/bin/node"];
  for (const c of candidates) {
    if (!existsSync(c)) continue;
    try {
      const r = spawnSync(c, ["--version"], { encoding: "utf8" });
      const major = Number((r.stdout || "").trim().replace(/^v/, "").split(".")[0]);
      if (r.status === 0 && major >= 18) return c;
    } catch {
      /* keep looking */
    }
  }
  return process.execPath;
}
const NODE = pickRelayNode();
const SUP_DIR = path.join(os.homedir(), ".apollo");

// Cross-platform Hermes home (mirrors relay.mjs).
function hermesHomeDir() {
  if (process.env.HERMES_HOME) return process.env.HERMES_HOME;
  return process.platform === "win32"
    ? path.join(os.homedir(), "AppData", "Local", "hermes")
    : path.join(os.homedir(), ".hermes");
}

function run(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: "utf8" });
  return { ok: r.status === 0, out: (r.stdout || "").trim(), err: (r.stderr || "").trim() };
}

// Escape a path for embedding inside a PowerShell single-quoted string.
const psq = (s) => s.replace(/'/g, "''");

console.log(`Apollo install`);
console.log(`  platform : ${process.platform} (${os.release()})`);
console.log(`  node     : ${NODE}`);
console.log(`  relay    : ${RELAY}`);
console.log(`  hermes   : ${hermesHomeDir()}`);

const major = Number(process.versions.node.split(".")[0]);
if (major < 18) {
  console.error(`\n!! Node ${process.versions.node} detected — Apollo needs Node >= 18.`);
  process.exit(1);
}

mkdirSync(SUP_DIR, { recursive: true });

if (process.platform === "win32") installWindows();
else if (process.platform === "linux") installLinux();
else if (process.platform === "darwin") installMac();
else {
  console.error(`\n!! Unsupported platform: ${process.platform}`);
  process.exit(1);
}

console.log(`\nDone. Next: in Chrome, chrome://extensions -> Developer mode -> Load unpacked ->`);
console.log(`  ${REPO}`);
console.log(`Open the Apollo side panel — the relay will connect automatically.`);

// --- Windows: schtasks watchdog (every 10 min, idempotent) -------------------
function installWindows() {
  const ps1 = path.join(SUP_DIR, "apollo-relay.ps1");
  const vbs = path.join(SUP_DIR, "apollo-relay-run.vbs");

  const ps1Lines = [
    "# Apollo relay watchdog — idempotent. Safe to run every N minutes.",
    "$ErrorActionPreference = 'SilentlyContinue'",
    "$node    = '" + psq(NODE) + "'",
    "$relay   = '" + psq(RELAY) + "'",
    "$workdir = '" + psq(REPO) + "'",
    "$logOut  = '" + psq(path.join(SUP_DIR, "apollo-relay.out.log")) + "'",
    "$logErr  = '" + psq(path.join(SUP_DIR, "apollo-relay.err.log")) + "'",
    "",
    "$listeners = Get-NetTCPConnection -LocalPort 8765 -State Listen",
    "$owners = @($listeners | Select-Object -ExpandProperty OwningProcess -Unique)",
    "if ($owners.Count -eq 1) { exit 0 }  # healthy single instance",
    "",
    "foreach ($p in $owners) { Stop-Process -Id $p -Force }",
    "Get-CimInstance Win32_Process -Filter \"Name='node.exe'\" |",
    "  Where-Object { $_.CommandLine -match 'relay\\.mjs' } |",
    "  ForEach-Object { Stop-Process -Id $_.ProcessId -Force }",
    "Start-Sleep -Seconds 2",
    "Start-Process -FilePath $node -ArgumentList $relay `",
    "  -WorkingDirectory $workdir -WindowStyle Hidden `",
    "  -RedirectStandardOutput $logOut -RedirectStandardError $logErr",
  ].join("\n");

  const vbsLines = [
    "' Apollo relay watchdog launcher (hidden). Generated by bridge/install.mjs",
    'CreateObject("WScript.Shell").Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ' + ps1 + '", 0, False',
  ].join("\n");

  writeFileSync(ps1, ps1Lines);
  writeFileSync(vbs, vbsLines);

  const r = run("schtasks", [
    "/Create", "/TN", "apollo-relay", "/SC", "MINUTE", "/MO", "10",
    "/TR", `wscript.exe "${vbs}"`, "/F",
  ]);
  if (r.ok) {
    console.log(`  supervisor: schtasks \\apollo-relay (every 10 min) -> ${vbs}`);
    console.log(`  scripts   : ${ps1}`);
  } else {
    console.warn(`  !! could not create the scheduled task (${r.err || "permission denied"}).`);
    console.warn(`     Run this once in an elevated prompt:`);
    console.warn(`       schtasks /Create /TN "apollo-relay" /SC MINUTE /MO 10 /TR "wscript.exe \\"${vbs}\\"" /F`);
  }
}

// --- Linux: systemd --user service ------------------------------------------
function installLinux() {
  const unitDir = path.join(os.homedir(), ".config", "systemd", "user");
  const unitPath = path.join(unitDir, "apollo-relay.service");
  mkdirSync(unitDir, { recursive: true });

  const unit = [
    "[Unit]",
    "Description=Apollo relay daemon (WS bridge between Chrome extension and Hermes MCP)",
    "After=network.target",
    "",
    "[Service]",
    `ExecStart=${NODE} ${RELAY}`,
    "Restart=on-failure",
    "",
    "[Install]",
    "WantedBy=default.target",
  ].join("\n");

  writeFileSync(unitPath, unit);
  run("systemctl", ["--user", "daemon-reload"]);
  const enable = run("systemctl", ["--user", "enable", "--now", "apollo-relay"]);
  const linger = run("loginctl", ["enable-linger", os.userInfo().username]);

  if (enable.ok) {
    console.log(`  supervisor: systemd --user apollo-relay.service (enabled)`);
    console.log(`  unit      : ${unitPath}`);
  } else {
    console.warn(`  !! systemctl --user failed (${enable.err}).`);
    console.warn(`     Start manually: systemctl --user enable --now apollo-relay`);
  }
  if (!linger.ok) {
    console.warn(`  !! loginctl enable-linger failed (${linger.err || "needs sudo"}) — the relay`);
    console.warn(`     stops when you log out. Run: sudo loginctl enable-linger $USER`);
  }
}

// --- macOS: launchd LaunchAgent ---------------------------------------------
function installMac() {
  const agentDir = path.join(os.homedir(), "Library", "LaunchAgents");
  const plistPath = path.join(agentDir, "com.apollo.relay.plist");
  mkdirSync(agentDir, { recursive: true });

  const plist = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0"><dict>',
    "  <key>Label</key><string>com.apollo.relay</string>",
    "  <key>ProgramArguments</key><array><string>" + NODE + "</string><string>" + RELAY + "</string></array>",
    "  <key>KeepAlive</key><true/>",
    "  <key>RunAtLoad</key><true/>",
    "</dict></plist>",
  ].join("\n");

  writeFileSync(plistPath, plist);
  const load = run("launchctl", ["load", plistPath]);
  console.log(`  supervisor: launchd com.apollo.relay (${load.ok ? "loaded" : load.err})`);
  console.log(`  plist     : ${plistPath}`);
}
